CREATE DATABASE IF NOT EXISTS `e2`;
USE `e2`;

DROP TABLE IF EXISTS `arte`;
DROP TABLE IF EXISTS `elemento`;
DROP TABLE IF EXISTS `gato`;
DROP TABLE IF EXISTS `heroi`;
DROP TABLE IF EXISTS `jogo`;
DROP TABLE IF EXISTS `metal_de_transicao`;
DROP TABLE IF EXISTS `monstro`;
DROP TABLE IF EXISTS `musica`;
DROP TABLE IF EXISTS `navio`;
DROP TABLE IF EXISTS `raposa`;

CREATE TABLE `arte` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`metodo` VARCHAR(50) NOT NULL,
	`tipo` VARCHAR(50) NOT NULL,
	`instrumento` VARCHAR(50) NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `elemento` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`tipo` VARCHAR(255) NOT NULL,
	`grau` TINYINT NOT NULL,
	`foco` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `gato` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`raca` VARCHAR(255) NOT NULL,
	`nome` VARCHAR(255) NOT NULL,
	`idade` TINYINT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `heroi` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `ataque` INTEGER NOT NULL,
	`defesa` INTEGER NOT NULL,
    `vida` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `jogo` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(255) NOT NULL UNIQUE,
    `genero` VARCHAR(50) NOT NULL,
	`tema` VARCHAR(50) NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `metal_de_transicao` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(255) NOT NULL UNIQUE,
	`numero_atomico` INTEGER NOT NULL,
	`densidade` FLOAT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `monstro` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(255) NOT NULL,
	`raca` VARCHAR(50) NOT NULL,
	`nivel` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `musica` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(255) NOT NULL,
    `segundos` INTEGER,
    `artista` VARCHAR(255),
	PRIMARY KEY(`id`)
);

CREATE TABLE `navio` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(255) NOT NULL,
	`classe` VARCHAR(255) NOT NULL,
    `ano_de_construcao` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `raposa` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `raca` VARCHAR(255) NOT NULL,
	`habitat` VARCHAR(255) NOT NULL,
	`cor` CHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);

ALTER TABLE `jogo`
ADD CONSTRAINT unique_nome UNIQUE (`nome`);

ALTER TABLE `metal_de_transicao`
ADD CONSTRAINT unique_name UNIQUE (`nome`);
